name: gentxt 
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.9.0
  - asn1crypto=1.3.0
  - blas=1.0
  - blinker=1.4
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=2.8
  - cudatoolkit=10.2.89
  - google-auth=1.13.1
  - google-auth-oauthlib=0.4.1
  - grpcio=1.27.2
  - idna=2.9
  - intel-openmp=2020.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libprotobuf=3.11.4
  - libstdcxx-ng=9.1.0
  - markdown=3.1.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - openssl=1.1.1g
  - pip=20.0.2
  - protobuf=3.11.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.2
  - pytorch=1.5.0
  - readline=8.0
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard=2.1.0
  - tk=8.6.8
  - torchtext=0.6.0
  - tqdm=4.45.0
  - urllib3=1.25.8
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11

